// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countChecklistItemHistory = `-- name: CountChecklistItemHistory :one
SELECT COUNT(*) FROM checklist_item_status_history WHERE checklist_item_id = ?
`

func (q *Queries) CountChecklistItemHistory(ctx context.Context, checklistItemID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChecklistItemHistory, checklistItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChecklistItemsForRelease = `-- name: CountChecklistItemsForRelease :one
SELECT COUNT(*) FROM checklist_items WHERE release_goal_id = ?
`

func (q *Queries) CountChecklistItemsForRelease(ctx context.Context, releaseGoalID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChecklistItemsForRelease, releaseGoalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistItem = `-- name: CreateChecklistItem :exec
INSERT INTO checklist_items (
    id, release_goal_id, title, description, requirement, category, requirement_level,
    source, source_reference, template_item_key, template_key, template_version,
    status, sort_order, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChecklistItemParams struct {
	ID               string
	ReleaseGoalID    string
	Title            string
	Description      string
	Requirement      string
	Category         string
	RequirementLevel string
	Source           string
	SourceReference  string
	TemplateItemKey  sql.NullString
	TemplateKey      sql.NullString
	TemplateVersion  sql.NullString
	Status           string
	SortOrder        int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) error {
	_, err := q.db.ExecContext(ctx, createChecklistItem,
		arg.ID,
		arg.ReleaseGoalID,
		arg.Title,
		arg.Description,
		arg.Requirement,
		arg.Category,
		arg.RequirementLevel,
		arg.Source,
		arg.SourceReference,
		arg.TemplateItemKey,
		arg.TemplateKey,
		arg.TemplateVersion,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createChecklistItemStatusHistory = `-- name: CreateChecklistItemStatusHistory :exec
INSERT INTO checklist_item_status_history (checklist_item_id, from_status, to_status, changed_at)
VALUES (?, ?, ?, ?)
`

type CreateChecklistItemStatusHistoryParams struct {
	ChecklistItemID string
	FromStatus      string
	ToStatus        string
	ChangedAt       string
}

func (q *Queries) CreateChecklistItemStatusHistory(ctx context.Context, arg CreateChecklistItemStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createChecklistItemStatusHistory,
		arg.ChecklistItemID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedAt,
	)
	return err
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT
    id, release_goal_id, title, description, requirement, category, requirement_level,
    source, source_reference, template_item_key, template_key, template_version,
    status, sort_order, created_at, updated_at
FROM checklist_items
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetChecklistItem(ctx context.Context, id string) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ReleaseGoalID,
		&i.Title,
		&i.Description,
		&i.Requirement,
		&i.Category,
		&i.RequirementLevel,
		&i.Source,
		&i.SourceReference,
		&i.TemplateItemKey,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT
    id, release_goal_id, title, description, requirement, category, requirement_level,
    source, source_reference, template_item_key, template_key, template_version,
    status, sort_order, created_at, updated_at
FROM checklist_items
WHERE release_goal_id = ?
    AND (?2 = '' OR status = ?2)
    AND (?3 = '' OR source = ?3)
    AND (?4 = '' OR category = ?4)
ORDER BY sort_order, id
`

type ListChecklistItemsParams struct {
	ReleaseGoalID  string
	StatusFilter   interface{}
	SourceFilter   interface{}
	CategoryFilter interface{}
}

func (q *Queries) ListChecklistItems(ctx context.Context, arg ListChecklistItemsParams) ([]ChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItems,
		arg.ReleaseGoalID,
		arg.StatusFilter,
		arg.SourceFilter,
		arg.CategoryFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGoalID,
			&i.Title,
			&i.Description,
			&i.Requirement,
			&i.Category,
			&i.RequirementLevel,
			&i.Source,
			&i.SourceReference,
			&i.TemplateItemKey,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChecklistSortOrder = `-- name: NextChecklistSortOrder :one
SELECT COALESCE(MAX(sort_order), 0) + 1
FROM checklist_items
WHERE release_goal_id = ?
`

func (q *Queries) NextChecklistSortOrder(ctx context.Context, releaseGoalID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextChecklistSortOrder, releaseGoalID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateChecklistItemStatus = `-- name: UpdateChecklistItemStatus :execrows
UPDATE checklist_items
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type UpdateChecklistItemStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
	Status_2  string
}

func (q *Queries) UpdateChecklistItemStatus(ctx context.Context, arg UpdateChecklistItemStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChecklistItemStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
