// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (
    id,
    name,
    description,
    location,
    location_key,
    steam_app_id,
    language,
    stage,
    status,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string
	Name        string
	Description string
	Location    string
	LocationKey string
	SteamAppID  sql.NullInt64
	Language    string
	Stage       string
	Status      string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.LocationKey,
		arg.SteamAppID,
		arg.Language,
		arg.Stage,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProject = `-- name: GetProject :one
SELECT
    id,
    name,
    description,
    location,
    location_key,
    steam_app_id,
    language,
    stage,
    status,
    created_at,
    updated_at
FROM projects
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.LocationKey,
		&i.SteamAppID,
		&i.Language,
		&i.Stage,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    id,
    name,
    description,
    location,
    location_key,
    steam_app_id,
    language,
    stage,
    status,
    created_at,
    updated_at
FROM projects
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.LocationKey,
			&i.SteamAppID,
			&i.Language,
			&i.Stage,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
