// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetRuntimeMetadata(ctx context.Context, key string) (string, error)
	Ping(ctx context.Context) (int64, error)
	UpsertRuntimeMetadata(ctx context.Context, arg UpsertRuntimeMetadataParams) error
}

var _ Querier = (*Queries)(nil)
