// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountChecklistItemHistory(ctx context.Context, checklistItemID string) (int64, error)
	CountChecklistItemsForRelease(ctx context.Context, releaseGoalID string) (int64, error)
	CountReleaseGoalHistory(ctx context.Context, releaseGoalID string) (int64, error)
	CountReleaseGoalsByProjectAndType(ctx context.Context, arg CountReleaseGoalsByProjectAndTypeParams) (int64, error)
	CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) error
	CreateChecklistItemStatusHistory(ctx context.Context, arg CreateChecklistItemStatusHistoryParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateReleaseGoal(ctx context.Context, arg CreateReleaseGoalParams) error
	CreateReleaseGoalStatusHistory(ctx context.Context, arg CreateReleaseGoalStatusHistoryParams) error
	GetChecklistItem(ctx context.Context, id string) (ChecklistItem, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetReleaseGoal(ctx context.Context, id string) (GetReleaseGoalRow, error)
	GetRuntimeMetadata(ctx context.Context, key string) (string, error)
	ListChecklistItems(ctx context.Context, arg ListChecklistItemsParams) ([]ChecklistItem, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListReleaseGoalsByProject(ctx context.Context, projectID string) ([]ListReleaseGoalsByProjectRow, error)
	NextChecklistSortOrder(ctx context.Context, releaseGoalID string) (int64, error)
	Ping(ctx context.Context) (int64, error)
	UpdateChecklistItemStatus(ctx context.Context, arg UpdateChecklistItemStatusParams) (int64, error)
	UpdateReleaseGoalStatus(ctx context.Context, arg UpdateReleaseGoalStatusParams) (int64, error)
	UpsertRuntimeMetadata(ctx context.Context, arg UpsertRuntimeMetadataParams) error
}

var _ Querier = (*Queries)(nil)
