// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	GetProject(ctx context.Context, id string) (Project, error)
	GetRuntimeMetadata(ctx context.Context, key string) (string, error)
	ListProjects(ctx context.Context) ([]Project, error)
	Ping(ctx context.Context) (int64, error)
	UpsertRuntimeMetadata(ctx context.Context, arg UpsertRuntimeMetadataParams) error
}

var _ Querier = (*Queries)(nil)
