// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package sqlc

import (
	"context"
)

const countReleaseGoalHistory = `-- name: CountReleaseGoalHistory :one
SELECT COUNT(*) FROM release_goal_status_history WHERE release_goal_id = ?
`

func (q *Queries) CountReleaseGoalHistory(ctx context.Context, releaseGoalID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleaseGoalHistory, releaseGoalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReleaseGoalsByProjectAndType = `-- name: CountReleaseGoalsByProjectAndType :one
SELECT COUNT(*) FROM release_goals WHERE project_id = ? AND goal_type = ?
`

type CountReleaseGoalsByProjectAndTypeParams struct {
	ProjectID string
	GoalType  string
}

func (q *Queries) CountReleaseGoalsByProjectAndType(ctx context.Context, arg CountReleaseGoalsByProjectAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleaseGoalsByProjectAndType, arg.ProjectID, arg.GoalType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReleaseGoal = `-- name: CreateReleaseGoal :exec
INSERT INTO release_goals (
    id, project_id, goal_type, title, status, template_key, template_version, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReleaseGoalParams struct {
	ID              string
	ProjectID       string
	GoalType        string
	Title           string
	Status          string
	TemplateKey     string
	TemplateVersion string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) CreateReleaseGoal(ctx context.Context, arg CreateReleaseGoalParams) error {
	_, err := q.db.ExecContext(ctx, createReleaseGoal,
		arg.ID,
		arg.ProjectID,
		arg.GoalType,
		arg.Title,
		arg.Status,
		arg.TemplateKey,
		arg.TemplateVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createReleaseGoalStatusHistory = `-- name: CreateReleaseGoalStatusHistory :exec
INSERT INTO release_goal_status_history (release_goal_id, from_status, to_status, changed_at)
VALUES (?, ?, ?, ?)
`

type CreateReleaseGoalStatusHistoryParams struct {
	ReleaseGoalID string
	FromStatus    string
	ToStatus      string
	ChangedAt     string
}

func (q *Queries) CreateReleaseGoalStatusHistory(ctx context.Context, arg CreateReleaseGoalStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createReleaseGoalStatusHistory,
		arg.ReleaseGoalID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedAt,
	)
	return err
}

const getReleaseGoal = `-- name: GetReleaseGoal :one
SELECT
    release_goals.id,
    release_goals.project_id,
    release_goals.goal_type,
    release_goals.title,
    release_goals.status,
    release_goals.template_key,
    release_goals.template_version,
    release_goals.created_at,
    release_goals.updated_at,
    COUNT(checklist_items.id) AS checklist_total,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.status = 'done' THEN 1 ELSE 0 END), 0) AS INTEGER) AS checklist_done,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.status = 'blocked' THEN 1 ELSE 0 END), 0) AS INTEGER) AS checklist_blocked,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.requirement_level = 'required' THEN 1 ELSE 0 END), 0) AS INTEGER) AS required_total,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.requirement_level = 'required' AND checklist_items.status = 'done' THEN 1 ELSE 0 END), 0) AS INTEGER) AS required_done
FROM release_goals
LEFT JOIN checklist_items ON checklist_items.release_goal_id = release_goals.id
WHERE release_goals.id = ?
GROUP BY release_goals.id
LIMIT 1
`

type GetReleaseGoalRow struct {
	ID               string
	ProjectID        string
	GoalType         string
	Title            string
	Status           string
	TemplateKey      string
	TemplateVersion  string
	CreatedAt        string
	UpdatedAt        string
	ChecklistTotal   int64
	ChecklistDone    int64
	ChecklistBlocked int64
	RequiredTotal    int64
	RequiredDone     int64
}

func (q *Queries) GetReleaseGoal(ctx context.Context, id string) (GetReleaseGoalRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseGoal, id)
	var i GetReleaseGoalRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalType,
		&i.Title,
		&i.Status,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.ChecklistBlocked,
		&i.RequiredTotal,
		&i.RequiredDone,
	)
	return i, err
}

const listReleaseGoalsByProject = `-- name: ListReleaseGoalsByProject :many
SELECT
    release_goals.id,
    release_goals.project_id,
    release_goals.goal_type,
    release_goals.title,
    release_goals.status,
    release_goals.template_key,
    release_goals.template_version,
    release_goals.created_at,
    release_goals.updated_at,
    COUNT(checklist_items.id) AS checklist_total,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.status = 'done' THEN 1 ELSE 0 END), 0) AS INTEGER) AS checklist_done,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.status = 'blocked' THEN 1 ELSE 0 END), 0) AS INTEGER) AS checklist_blocked,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.requirement_level = 'required' THEN 1 ELSE 0 END), 0) AS INTEGER) AS required_total,
    CAST(COALESCE(SUM(CASE WHEN checklist_items.requirement_level = 'required' AND checklist_items.status = 'done' THEN 1 ELSE 0 END), 0) AS INTEGER) AS required_done
FROM release_goals
LEFT JOIN checklist_items ON checklist_items.release_goal_id = release_goals.id
WHERE release_goals.project_id = ?
GROUP BY release_goals.id
ORDER BY release_goals.created_at DESC, release_goals.id DESC
`

type ListReleaseGoalsByProjectRow struct {
	ID               string
	ProjectID        string
	GoalType         string
	Title            string
	Status           string
	TemplateKey      string
	TemplateVersion  string
	CreatedAt        string
	UpdatedAt        string
	ChecklistTotal   int64
	ChecklistDone    int64
	ChecklistBlocked int64
	RequiredTotal    int64
	RequiredDone     int64
}

func (q *Queries) ListReleaseGoalsByProject(ctx context.Context, projectID string) ([]ListReleaseGoalsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseGoalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseGoalsByProjectRow{}
	for rows.Next() {
		var i ListReleaseGoalsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GoalType,
			&i.Title,
			&i.Status,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChecklistTotal,
			&i.ChecklistDone,
			&i.ChecklistBlocked,
			&i.RequiredTotal,
			&i.RequiredDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReleaseGoalStatus = `-- name: UpdateReleaseGoalStatus :execrows
UPDATE release_goals
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type UpdateReleaseGoalStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
	Status_2  string
}

func (q *Queries) UpdateReleaseGoalStatus(ctx context.Context, arg UpdateReleaseGoalStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateReleaseGoalStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
