// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime.sql

package sqlc

import (
	"context"
)

const getRuntimeMetadata = `-- name: GetRuntimeMetadata :one
SELECT value
FROM corvus_runtime_metadata
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetRuntimeMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}

const upsertRuntimeMetadata = `-- name: UpsertRuntimeMetadata :exec
INSERT INTO corvus_runtime_metadata (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertRuntimeMetadataParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) UpsertRuntimeMetadata(ctx context.Context, arg UpsertRuntimeMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertRuntimeMetadata, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
